#!/usr/bin/env bash
# transfers a file from the client to the server
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
if [[ $# -lt 3 ]];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    if [[ -z $4 ]];
    then 
        scp -T "$1" "$3@$2:/"
    else
        scp -T "$1" "$3@$2:/$4"
    fi
fi