#!/usr/bin/env bash
# configures nginx so that /redirect_me is redirecting to another page.
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "37a\ $redirect" /etc/nginx/sites-enabled/default
sudo service nginx start
