#!/usr/bin/env bash
# displays numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5

i=1
while [ $i -le 100 ]
do
    modt=$(( i%3 ))
    modf=$(( i%5 ))
    if [ $modt = 0 ] && [ $modf = 0 ]
    then
        echo "FizzBuzz"
    elif [ $modt = 0 ]
    then
        echo "Fizz"
    elif [ $modf = 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    i=$(( i+1 ))
done
